# Generated by Django 3.0.5 on 2020-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('emailid', models.EmailField(blank=True, default='', max_length=70, null=True)),
                ('phoneno', models.CharField(blank=True, default='', max_length=70, null=True)),
            ],
        ),
    ]
